// frameworks/vue/src/App.vue
<template>
  <main>
    <div class="header">
      <h1>Vue</h1>
      <div class="actions">
        <button id="create" @click="() => rows = buildData(1000)">Create</button>
        <button id="reverse" @click="() => rows = rows.toReversed()">Reverse</button>
        <button id="insert"
          @click="() => rows = [...rows.slice(0, 10), ...buildData(1), ...rows.slice(10)]">Insert</button>
        <button id="prepend" @click="() => rows = [...buildData(1), ...rows]">Prepend</button>
        <button id="append" @click="() => rows = [...rows, ...buildData(1)]">Append</button>
        <button id="sort" @click="() => rows = rows.toSorted((a, b) => a.name.localeCompare(b.name))">Sort</button>
        <button id="filter" @click="() => rows = rows.filter(d => d.id % 2)">Filter</button>
        <button id="units" @click="() => unitSystem = unitSystem === 'imperial' ? 'metric' : 'imperial'">Units</button>
        <button id="restock" @click="() => rows = rows.map(r => r.availabilityStatus === 'Out of Stock'
          ? { ...r, availabilityStatus: 'In Stock' }
          : r)">Restock</button>
        <button id="clear" @click="() => rows = []">Clear</button>
      </div>
    </div>

    <table v-if="rows.length">
      <thead>
        <tr>
          <th>id</th>
          <th>name</th>
          <th>weight</th>
          <th>dimensions</th>
          <th>power consumption</th>
          <th>price</th>
          <th>availability status</th>
          <th>rating</th>
          <th>actions</th>
        </tr>
      </thead>
      <tbody>
        <Row v-for="row in rows" :key="row.id" :row="row" :selected="selected" :unitSystem="unitSystem"
          :weightConversion="weightConversion" :lengthConversion="lengthConversion" :powerConversion="powerConversion"
          @select="selected = $event" @delete="rows = rows.filter(r => r.id !== row.id)" />
      </tbody>
    </table>

    <h2 v-else class="text-center">No rows to show</h2>
  </main>
</template>

<script setup>
import { buildData } from 'common/data'
import { computed, ref } from 'vue'
import Row from './Row.vue'

const rows = ref([])
const selected = ref(null)
const unitSystem = ref("metric")

const weightConversion = computed(() =>
  unitSystem.value === "metric" ? 1 : 2.20462
)
const powerConversion = computed(() =>
  unitSystem.value === "metric" ? 1 : 0.00134102
)
const lengthConversion = computed(() =>
  unitSystem.value === "metric" ? 1 : 0.393701
)
</script>

// frameworks/react/src/App.jsx
import { buildData } from 'common/data';
import { useMemo, useState } from 'react';
import Row from './Row';

export default function App() {
  const [rows, setRows] = useState([]);
  const [selected, setSelected] = useState(null);
  const [unitSystem, setUnitSystem] = useState('metric');

  const weightConversion = useMemo(
    () => (unitSystem === 'metric' ? 1 : 2.20462),
    [unitSystem]
  );

  const powerConversion = useMemo(
    () => (unitSystem === 'metric' ? 1 : 0.00134102),
    [unitSystem]
  );

  const lengthConversion = useMemo(
    () => (unitSystem === 'metric' ? 1 : 0.393701),
    [unitSystem]
  );

  return (
    <main>
      <div className="header">
        <h1>React</h1>
        <div className="actions">
          <button id="create" onClick={() => setRows(buildData(1000))}>Create</button>
          <button id="reverse" onClick={() => setRows([...rows].toReversed())}>Reverse</button>
          <button id="insert" onClick={() =>
            setRows([...rows.slice(0, 10), ...buildData(1), ...rows.slice(10)])
          }>
            Insert
          </button>
          <button id="prepend" onClick={() => setRows([...buildData(1), ...rows])}>
            Prepend
          </button>
          <button id="append" onClick={() => setRows([...rows, ...buildData(1)])}>
            Append
          </button>
          <button id="sort" onClick={() =>
            setRows([...rows].toSorted((a, b) => a.name.localeCompare(b.name)))
          }>
            Sort
          </button>
          <button id="filter" onClick={() => setRows(rows.filter((d) => d.id % 2))}>
            Filter
          </button>
          <button id="units" onClick={() =>
            setUnitSystem(unitSystem === 'imperial' ? 'metric' : 'imperial')
          }>
            Units
          </button>
          <button id="restock" onClick={() =>
            setRows(rows => rows.map(r => r.availabilityStatus === "Out of Stock" ? { ...r, availabilityStatus: "In Stock" } : r))
          }>
            Restock
          </button>
          <button id="clear" onClick={() => setRows([])}>Clear</button>
        </div>
      </div>

      {rows.length ? (
        <table>
          <thead>
            <tr>
              <th>id</th>
              <th>name</th>
              <th>weight</th>
              <th>dimensions</th>
              <th>power consumption</th>
              <th>price</th>
              <th>availability status</th>
              <th>rating</th>
              <th>actions</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row) => (
              <Row
                key={row.id}
                row={row}
                selected={selected}
                setSelected={setSelected}
                setRows={setRows}
                rows={rows}
                unitSystem={unitSystem}
                weightConversion={weightConversion}
                lengthConversion={lengthConversion}
                powerConversion={powerConversion}
              />
            ))}
          </tbody>
        </table>
      ) : (
        <h2 className="text-center">No rows to show</h2>
      )}
    </main>
  );
}
